const actions = {
  FORUMPAGECHANGE: 'FORUMPAGECHANGE',
  UPDATESEARCHSKILLS: 'UPDATESEARCHSKILLS',
  UPDATESEARCHTYPES: 'UPDATESEARCHTYPES',
  TOGGLELOADING: 'TOGGLELOADING',
  UPDATERECOMTYPES: 'UPDATERECOMTYPES',
  TOGGLESTATE: 'TOGGLESTATE',
  // UPDATERECOMTYPES: 'UPDATERECOMTYPES',
  // UPDATERECOMTYPES: 'UPDATERECOMTYPES',
};

export default actions;
