const actions = {
  FORUMPAGECHANGE: 'FORUMPAGECHANGE',
  UPDATESEARCHSKILLS: 'UPDATESEARCHSKILLS',
  UPDATESEARCHTYPES: 'UPDATESEARCHTYPES',
  TOGGLELOADING: 'TOGGLELOADING',
  // LOGIN_FAILURE: 'LOGIN_FAILURE',
};

export default actions;
