const actions = {
  FORUMPAGECHANGE: 'FORUMPAGECHANGE',
  UPDATESEARCHSKILLS: 'UPDATESEARCHSKILLS',
  UPDATESEARCHTYPES: 'UPDATESEARCHTYPES',
  UPDATERECOMTYPES: 'UPDATERECOMTYPES',

  GETFEEDS: 'GETFEEDS',
  GETFEEDS_SUCCESS: 'GETFEEDS_SUCCESS',
  GETFEEDS_FAILURE: 'GETFEEDS_FAILURE',
  FEEDLOADING: 'FEEDLOADING',
  ADDFEEDS: 'ADDFEEDS',
  ADDFEEDS_SUCCESS: 'ADDFEEDS_SUCCESS',
  ADDFEEDS_FAILURE: 'ADDFEEDS_FAILURE',

  GETRECOMM: 'GETRECOMM',
  GETRECOMM_SUCCESS: 'GETRECOMM_SUCCESS',
  GETRECOMM_FAILURE: 'GETRECOMM_FAILURE',
  RECOMMLOADING: 'RECOMMLOADING',
  ADDRECOMM: 'ADDRECOMM',
  ADDRECOMM_SUCCESS: 'ADDRECOMM_SUCCESS',
  ADDRECOMM_FAILURE: 'ADDRECOMM_FAILURE',

  SEARCHFEEDS: 'SEARCHFEEDS',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAILURE: 'SEARCH_FAILURE',
  UPDATESEARCHSTRING: 'UPDATESEARCHSTRING',

  TOGGLELOADING: 'TOGGLELOADING',
  TOGGLESTATE: 'TOGGLESTATE',

  ADDPOST: 'ADDPOST',
  ADDPOST_SUCCESS: 'ADDPOST_SUCCESS',
  ADDPOST_FAILURE: 'ADDPOST_FAILURE',

  FORCEUPDATE: 'FORCEUPDATE',

  ADDCOMMENT: 'ADDCOMMENT',
  ADDCOMMENT_SUCCESS: 'ADDCOMMENT_SUCCESS',
  ADDCOMMENT_FAILURE: 'ADDCOMMENT_FAILURE',

  // ADDRECOMM: 'ADDRECOMM',
  // ADDRECOMM: 'ADDRECOMM',
  // ADDRECOMM: 'ADDRECOMM',
  // ADDRECOMM: 'ADDRECOMM',
};

export default actions;
